version: "3.8"

services:
  pagerenderapi:
    build: .
    container_name: pagerenderapi
    environment:
      PGUSER: ${PGUSER} 
      PGPASSWORD: ${PGPASSWORD} 
      PGHOST: postgres
      PGPORT: ${PGPORT} 
      PGDATABASE: ${PGDATABASE} 
      AWS_BUCKET: ${AWS_BUCKET} 
      AWS_REGION: ${AWS_REGION} 
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY} 
      AWS_SECRET_KEY: ${AWS_SECRET_KEY} 
      AWS_S3_ENDPOINT: http://localstack:4566 
    ports:
      - "4000:4000"
    depends_on:
      - localstack
      - create-bucket
      - postgres
